api_config:
  login_api:
    phase: "init"
    name: "01_authentication_api"
    is_auth_api: true
    method: POST
    url: "https://dummyjson.com/auth/login"
    headers:
      Content-Type: "application/json"
    payload:
      username: "emilys"
      password: "emilyspass"
      expiresInMins: 2
    response_mapping:
      extractors:
        access_token: $.accessToken

  get_user_data:
    phase: "action"
    name: "02_user_data"
    url: "https://dummyjson.com/auth/me"
    method: "GET"
    headers:
      Authorization: "Bearer ${access_token}"
    depends_on: "01_authentication_api"
#
#  post_user_data:
#    phase: "action"
#    name: "03_post_user_data"
#    url: "https://api.example.com/users/{user_id}"
#    method: "POST"
#    headers:
#      Authorization: "Bearer ${access_token}"
#    depends_on: "01_authentication_api"
#
#  logout_api:
#    name: "04_logout_user"
#    phase: "end"
#    url: "https://api.example.com/logout"
#    method: "GET"
#    headers:
#      Authorization: "Bearer ${access_token}"
#    depends_on: "01_authentication_api"
